# Generated by Django 4.0.3 on 2022-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='repo_url',
            field=models.URLField(default='https://github.com/jyanpico'),
            preserve_default=False,
        ),
    ]
