# Generated by Django 4.0.3 on 2022-04-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dashboardpanel_panel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='repo_description',
            field=models.CharField(default='Chart of the lanugages used in this really cool GitHub Repo!!!', max_length=300),
            preserve_default=False,
        ),
    ]
